const List<Map<String, dynamic>> serviceCategories = [
  {"name": "Electricians", "value": "electrician"},
  {"name": "Plumbers", "value": "Plumbers"},
  {"name": "Ac Service & Repair", "value": "acservice"},
  {"name": "IT services", "value": "itservices"},
  {"name": "Painters", "value": "painter"},
  {"name": "Salon & Spa", "value": "salon"},
  {"name": "Cleaning & Disinfection", "value": "cleaning"},
  {"name": "Cabs", "value": "cabs"},
  {"name": "Carpenters", "value": "carpenters"},
  {"name": "Packers & Movers", "value": "packersmovers"},
  {"name": "Hotels", "value": "hotels"},
  {"name": "Hostels", "value": "hostels"},
  {"name": "Insurance", "value": "insurance"},
  {"name": "Construction", "value": "construction"},
  {"name": "Interior Designing", "value": "interiordesigning"},
  {"name": "Coaching", "value": "coaching"},
  {"name": "Doctors", "value": "doctors"},
  {"name": "Dry Cleaners", "value": "drycleaners"},
  {"name": "Tent House", "value": "Tenthouse"},
  {"name": "Telecom Services", "value": "telecomservices"},
  {"name": "Courier services", "value": "courierservices"},
  {"name": "Mechanics", "value": "mechanics"},
  {"name": "Gyms & Fitness", "value": "gyms"},
  {"name": "Pest Control", "value": "pestcontrol"},
  {"name": "Event Planning", "value": "eventplanning"},
  {"name": "Car Service", "value": "carservice"},
  {"name": "Photography", "value": "photography"},
  {"name": "Astrology", "value": "astrology"},
  {"name": "Drivers", "value": "drivers"},
  {"name": "Education/Singing/Dancing", "value": "educationSinging"},
  {"name": "Advertising and Marketing", "value": "Advertisingmarketing"},
  {"name": "Food & Catering", "value": "catering"},
  {"name": "Financial & Auditing", "value": "financialauditing"},
  {"name": "Appliance Repair", "value": "appliancerepair"},
  {"name": "Charities", "value": "charities"},
  {"name": "Other Services", "value": "otherService"}
];
