const List<Map<String, dynamic>> storeCategories = [
  {"name": "Grocery & Super Market", "value": "grocery"},
  {"name": "Nuts & Spices", "value": "Nutsandspices"},
  {"name": "Meat stores", "value": "Meatstores"},
  {"name": "Pooja Stores", "value": "Poojastores"},
  {"name": "Health & Glow", "value": "healthandwellness"},
  {"name": "Milk & Dairy", "value": "dairy"},
  {"name": "Fruits & Vegetables", "value": "fruitsvegs"},
  {"name": "Beauty Parlors", "value": "beautyparlors"},
  {"name": "Ayurveda", "value": "ayurveda"},
  {"name": "Pharmacy", "value": "pharmacy"},
  {"name": "Kids & Toys", "value": "Toys"},
  {"name": "Gift Shops", "value": "giftshop"},
  {"name": "Textile & Clothing", "value": "textiles"},
  {"name": "Food & Baverages", "value": "restaurants"},
  {"name": "Footwear", "value": "footwear"},
  {"name": "Beauty products", "value": "beauty"},
  {"name": "Books & Stationary", "value": "bookstores"},
  {"name": "Organic Products", "value": "organicproducts"},
  {"name": "Sweet Shop", "value": "sweetshop"},
  {"name": "Fashion & Boutiques", "value": "fashion"},
  {"name": "Pan Shop", "value": "panshop"},
  {"name": "Farmers", "value": "farmers"},
  {"name": "Weavers", "value": "weavers"},
  {"name": "Electronics & Accessories", "value": "electronics"},
  {"name": "Hardware & Home Decor", "value": "hardware"},
  {"name": "Travel & Insurance", "value": "insurance"},
  {"name": "Banking & Finance", "value": "banking"},
  {"name": "Home Appliances", "value": "homeneeds"},
  {"name": "Novelty", "value": "novelty"},
  {"name": "Mobiles & Accessories", "value": "mobiles"},
  {"name": "Sports & Adventure", "value": "sports"},
  {"name": "Furniture", "value": "furniture"},
  {"name": "Automobiles & Parts", "value": "automobiles"},
  {"name": "Computer Hardware", "value": "computer"},
  {"name": "Other stores", "value": "otherstores"}
];
